name: Points System BE

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2.4'
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.1
    - name: List files in the current directory
      run: ls -la
    - name: Install npm
      run: npm install
      working-directory: ./
    - name: Generate Laravel Encryption Key
      run: php artisan key:generate
    - uses: actions/checkout@v3
    - name: Create .env file from .env.test
      run: cp .env.test .env
    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Update Composer Lock File
      run: composer update --no-scripts --no-progress

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass
    - name: Update known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p 65002 151.106.124.122 >> ~/.ssh/known_hosts
          
    - name: Create remote directory (if not exists)
      run: |
          sshpass -p '${{ secrets.SSH_PASS }}' ssh -p 65002 u102654923@151.106.124.122 "mkdir -p /home/u102654923/domains/denzellanzaderas.online/public_html/loyalty-points-be"
    - name: Deploy to Hostinger
      run: |
          sshpass -p '${{ secrets.SSH_PASS }}' rsync -avz -e "ssh -p 65002" ./ u102654923@151.106.124.122:/home/u102654923/domains/denzellanzaderas.online/public_html/loyalty-points-be
