name: Production Deployment

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'


   
    - uses: actions/checkout@v3
    - name: Create .env file from .env.production
      run: cp .env.production .env


    - name: Update Composer Lock File
      run: composer update --no-scripts --no-progress

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate Laravel Encryption Key
      run: php artisan key:generate
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.1
    - name: Install npm
      run: npm install
    - name: Create .htaccess file
      run: |
        cat <<EOL > .htaccess
        <IfModule mod_rewrite.c>
            Options +FollowSymLinks
            RewriteEngine On
            RewriteCond %{REQUEST_URI} !^/public/
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^(.*)$ /public/$1
            #RewriteRule ^ index.php [L]
            RewriteRule ^(/)?$ public/index.php [L]
        </IfModule>
        EOL
        
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass
    - name: Update known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p 22 31.220.55.56 >> ~/.ssh/known_hosts
          
    - name: Create remote directory (if not exists)
      run: |
          echo '${{ secrets.SSH_PROD }}' | sshpass -p '${{ secrets.SSH_PROD }}' ssh -t root@31.220.55.56 "sudo -S mkdir -p /home/ubuntu/be.dltprimeventures.com/public_html"
    - name: Deploy to Hostinger
      run: |
          sshpass -p '${{ secrets.SSH_PROD }}' rsync -avz -e "ssh -p 22" ./ root@31.220.55.56:/home/ubuntu/be.dltprimeventures.com/public_html
          echo '${{ secrets.SSH_PROD }}' | sshpass -p '${{ secrets.SSH_PROD }}' ssh -t root@31.220.55.56 "sudo -S chown www-data:www-data -R /home/ubuntu/be.dltprimeventures.com/public_html"
